// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/shape.ts
var toProductJson = (row) => ({
  id: String(row.id ?? ""),
  name: String(row.name ?? ""),
  category: String(row.category ?? ""),
  price: Number(row.price ?? 0),
  purchase_price: row.purchase_price == null ? null : Number(row.purchase_price),
  wholesale_price: row.wholesale_price == null ? null : Number(row.wholesale_price),
  internal_code: row.internal_code == null ? null : String(row.internal_code),
  international_code: row.international_code == null ? null : String(row.international_code),
  sizes: row.sizes == null ? null : String(row.sizes),
  specifications: row.specifications == null ? null : String(row.specifications),
  benefits: Array.isArray(row.benefits) ? row.benefits.map((b) => String(b)) : [],
  image_url: row.image_url == null ? null : String(row.image_url),
  additional_images: Array.isArray(row.additional_images) ? row.additional_images.map((i) => String(i)) : [],
  created_at: row.created_at == null ? null : String(row.created_at),
  updated_at: row.updated_at == null ? null : String(row.updated_at)
});
var toOfferJson = (row) => ({
  id: String(row.id ?? ""),
  product_name: String(row.product_name ?? ""),
  old_price: Number(row.old_price ?? 0),
  new_price: Number(row.new_price ?? 0),
  discount_percent: Number(row.discount_percent ?? 0),
  emoji: row.emoji == null ? null : String(row.emoji),
  active: Boolean(row.active),
  expires_at: row.expires_at == null ? null : String(row.expires_at),
  created_at: row.created_at == null ? null : String(row.created_at)
});

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List or search the store catalog. Optionally filter by category or by a text query matching the product name, internal code, or international code.",
  inputSchema: {
    query: z.string().trim().optional().describe("Text to match in name or product codes."),
    category: z.string().trim().optional().describe("Exact category name to filter by."),
    limit: z.number().int().min(1).max(100).optional().describe("Maximum rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let request = supabaseForUser(ctx).from("products").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (category) request = request.eq("category", category);
    if (query)
      request = request.or(
        `name.ilike.%${query}%,internal_code.ilike.%${query}%,international_code.ilike.%${query}%`
      );
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const products = (data ?? []).map(toProductJson);
    return {
      content: [{ type: "text", text: JSON.stringify(products) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch one product with all its details, by id or by internal code.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("Product id."),
    internal_code: z2.string().trim().optional().describe("Internal product code.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, internal_code }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (!id && !internal_code)
      return { content: [{ type: "text", text: "Provide id or internal_code" }], isError: true };
    let request = supabaseForUser(ctx).from("products").select("*").limit(1);
    request = id ? request.eq("id", id) : request.eq("internal_code", internal_code);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    const product = toProductJson(data[0]);
    return {
      content: [{ type: "text", text: JSON.stringify(product) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-offers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^3.25.76";
var list_offers_default = defineTool3({
  name: "list_offers",
  title: "List offers",
  description: "List the store's promotional offers. By default only active, non-expired offers.",
  inputSchema: {
    include_inactive: z3.boolean().optional().describe("Include inactive and expired offers (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_inactive }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let request = supabaseForUser(ctx).from("offers").select("*").order("created_at", { ascending: false });
    if (!include_inactive) request = request.eq("active", true);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const now = Date.now();
    const offers = (data ?? []).map(toOfferJson).filter(
      (offer) => include_inactive || !offer.expires_at || new Date(offer.expires_at).getTime() > now
    );
    return {
      content: [{ type: "text", text: JSON.stringify(offers) }],
      structuredContent: { offers }
    };
  }
});

// src/lib/mcp/tools/create-product.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z4 } from "npm:zod@^3.25.76";
var create_product_default = defineTool4({
  name: "create_product",
  title: "Create product",
  description: "Add a new product to the store catalog.",
  inputSchema: {
    name: z4.string().trim().min(1).describe("Product name."),
    category: z4.string().trim().min(1).describe("Product category."),
    internal_code: z4.string().trim().min(1).describe("Internal product code (required)."),
    price: z4.number().nonnegative().describe("Retail selling price."),
    wholesale_price: z4.number().nonnegative().optional().describe("Wholesale price."),
    purchase_price: z4.number().nonnegative().optional().describe("Purchase cost price."),
    international_code: z4.string().trim().optional().describe("International barcode (optional)."),
    sizes: z4.string().trim().optional().describe("Available sizes, free text."),
    specifications: z4.string().trim().optional().describe("Product specifications, free text."),
    image_url: z4.string().url().optional().describe("Main image URL.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("products").insert({ ...input, created_by: ctx.getUserId() }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const product = toProductJson(data?.[0] ?? {});
    return {
      content: [{ type: "text", text: JSON.stringify(product) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/update-product.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z5 } from "npm:zod@^3.25.76";
var update_product_default = defineTool5({
  name: "update_product",
  title: "Update product",
  description: "Update fields of an existing product. Only the fields you pass are changed.",
  inputSchema: {
    id: z5.string().uuid().describe("Id of the product to update."),
    name: z5.string().trim().min(1).optional(),
    category: z5.string().trim().min(1).optional(),
    internal_code: z5.string().trim().min(1).optional(),
    international_code: z5.string().trim().optional(),
    price: z5.number().nonnegative().optional(),
    wholesale_price: z5.number().nonnegative().optional(),
    purchase_price: z5.number().nonnegative().optional(),
    sizes: z5.string().trim().optional(),
    specifications: z5.string().trim().optional(),
    image_url: z5.string().url().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ id, ...patch }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const fields = Object.fromEntries(
      Object.entries(patch).filter(([, value]) => value !== void 0)
    );
    if (!Object.keys(fields).length)
      return { content: [{ type: "text", text: "No fields to update" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("products").update({ ...fields, updated_at: (/* @__PURE__ */ new Date()).toISOString() }).eq("id", id).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    const product = toProductJson(data[0]);
    return {
      content: [{ type: "text", text: JSON.stringify(product) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zdpdxthzzwsogilhxnyz";
var mcp_default = defineMcp({
  name: "my-app-mcp",
  title: "\u0627\u0644\u0627\u062E\u0648\u0647 \u0644\u062A\u062C\u0647\u064A\u0632\u0627\u062A \u0627\u0644\u0639\u0631\u0627\u0626\u0633",
  version: "0.1.0",
  instructions: "Tools for the bridal and home-appliance store catalog. Use `list_products` to search the catalog, `get_product` for full details of one item, `list_offers` for current promotions, and `create_product` / `update_product` to manage catalog entries.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_product_default, list_offers_default, create_product_default, update_product_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
